export enum OrderStatus {
  ORDER_PENDING = 'ORDER_PENDING',
  ORDER_PLACED = 'ORDER_PLACED',
  ORDER_FAILED = 'ORDER_FAILED', // DUE TO PAYMENT FAILED BY ANY REASON
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  ORDER_SHIPPED = 'ORDER_SHIPPED',
  ORDER_COMPLETED = 'ORDER_COMPLETED',
  ORDER_DELIVERED = 'ORDER_DELIVERED',
  ORDER_PARTIALLY_DELIVERED = 'ORDER_PARTIALLY_DELIVERED', // WHEN LARGE QTY ORDER SHIPPED WITH MORE THAN 1 TRACKING ID
  ORDER_PROCESSING = 'ORDER_PROCESSING',
}
export enum ShippingCarrier {
  USPS = 'USPS',
  UPS = 'UPS',
  FEDEX = 'FEDEX',
  DHL = 'DHL',
}

export enum paymentResponse {
  PAYMENT_OPEN = 'PAYMENT_OPEN', //this response will be used when payment is initiated but not confirmed.
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_CANCELED = 'PAYMENT_CANCELED',
}

export enum PaymentMethod {
  STRIPE = 'STRIPE',
  CARD = 'CARD',
  PAYPAL = 'PAYPAL',
}
